### ISSUE TITLE
Throw exception when headers are already sent 

### ISSUE THREAD

**Issue by mosbth** [mosbth/Anax-MVC#11]
Provide a better error message when headers are already sent, throw exception and display the the callback trace to see which methods are involved.

Use headers_sent() to detect the issue.

**Comment by mosbth** [comment]
You can try it out at `webroot/test/headers-already-sent`

Should look a bit like this:
Simulating outputhejAnax: Uncaught exception:

Trying to send headers but headers already sent, output started at /home/mos/git/Anax-MVC/webroot/test/error-message-verbosity.php line 121.

Code: 0

#0 /home/mos/git/Anax-MVC/src/Response/CResponseBasic.php(100): Anax\Response\CResponseBasic->checkIfHeadersAlreadySent()
#1 /home/mos/git/Anax-MVC/webroot/test/error-message-verbosity.php(122): Anax\Response\CResponseBasic->redirect('http://example....')
#2 [internal function]: TestController->headersAlreadySentAction()
#3 /home/mos/git/Anax-MVC/src/MVC/CDispatcherBasic.php(181): call_user_func_array(Array, Array)
#4 /home/mos/git/Anax-MVC/src/Route/CRouterBasic.php(123): Anax\MVC\CDispatcherBasic->dispatch()
#5 /home/mos/git/Anax-MVC/webroot/test/error-message-verbosity.php(171): Anax\Route\CRouterBasic->handle()
#6 {main}
